ServerName localhost

DocumentRoot "/usr/local/apache2/htdocs/"

<Directory "/usr/local/apache2/htdocs/">

    AllowOverride None
    Require all granted

    <LimitExcept GET POST HEAD>
        Require all denied
    </LimitExcept>

</Directory>

DirectoryIndex index.html

ServerTokens Prod
ServerSignature Off
