services:
    web:
      build: ./app
      container_name: my-apache-ssl
      volumes:
          - ./app/src:/var/www/html
      depends_on:
          - db
      restart: unless-stopped
    
    db:
      image: mysql:8.0
      container_name: mysql-db
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: app_db
        MYSQL_USER: app_user
        MYSQL_PASSWORD: app_pass
      volumes:
        - mysql_data:/var/lib/mysql
      restart: unless-stopped

volumes:
    mysql_data: